$: dropin.recipes/Automations/Deployment

services:
  kiwi-runtime-vscode:
    runtime: { name: nodejs }
    dependencies:
      kiwi-bundle: blueforest:kiwi/core:kiwi-bundle:v1
      kiwi-bundle-vscode: blueforest:kiwi/vscode:kiwi-bundle-vscode:v1
      dropin-recipes: blueforest:dropin/recipes:dropin-recipes-js:v1
    tasks:
      - name: Start developement build
        command: start
      - name: Build production files
        command: build
